name: Stage DB Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-stage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Download Cloud SQL Auth Proxy
        run: |
          curl -o cloud-sql-proxy https://dl.google.com/cloudsql/cloud-sql-proxy.linux.amd64
          chmod +x cloud-sql-proxy

      - name: Start Cloud SQL Auth Proxy
        run: |
          ./cloud-sql-proxy ${{ secrets.CLOUDSQL_INSTANCE_CONNECTION }} &
          sleep 5

      - name: Install Liquibase
        run: |
          curl -Lo liquibase.zip https://github.com/liquibase/liquibase/releases/download/v4.29.2/liquibase-4.29.2.zip
          sudo apt-get update && sudo apt-get install -y unzip
          unzip liquibase.zip -d liquibase-cli
          sudo mv liquibase-cli /opt/liquibase
          sudo ln -s /opt/liquibase/liquibase /usr/local/bin/liquibase
          liquibase --version

      - name: Run Liquibase on Stage
        run: |
          liquibase \
            --url="${{ secrets.DB_STAGE_URL }}" \
            --username=${{ secrets.DB_USER }} \
            --password=${{ secrets.DB_PASS }} \
            tag "build-${GITHUB_RUN_NUMBER}"
          liquibase \
            --url="${{ secrets.DB_STAGE_URL }}" \
            --username=${{ secrets.DB_USER }} \
            --password=${{ secrets.DB_PASS }} \
            update

